### PR TITLE
add CPUInfoActivity

### PR DESCRIPTION
**Pull request by paulvi**
as it is on http://android-er.blogspot.in/2009/09/read-android-cpu-info.html (keeping author's link)

See also http://stackoverflow.com/questions/29231207/android-check-if-it-is-arm-or-intel-cpu-64-or-32bit

### CODE REVIEW

**Comment by takke** [comment]
thanks your PR :+1: 

I have a question.
Why we have to keep the link of the blog in the new activity ?
Can you remove it ?

**Comment by paulvi** [comment]
The code was just copied, so I am trying to give credits.

Look at #4 

I think About page should have soming like

```
Cpustats. Created by @takke  
using cpuid code from ...
```

than it would be OK to remove that not so nice looking link.

**Comment by takke** [comment]
Added "About" activity
and merged CPUInfoActivity into "About" activity.

https://github.com/takke/cpustats/commit/1e4675b8562cea96aa935a45b816745500fd8bec

**Comment by paulvi** [comment]
let's continue in #4

**Pull request merged**
